# Site
name: "Keelan Cook"
title: "Keelan Cook"
description: "George Liele Director of the Center for Great Commission Studies"
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
baseurl: /mediumish
google_analytics: 'UA-46278016-1'
disqus: ''
mailchimp-list: 'https://keelancook.us18.list-manage.com/subscribe/post?u=c5bc34a16760b316bee44bff4&amp;id=dfa9780140&amp;f_id=00a98ae6f0'
include: ["_pages"]
permalink: /:year/:month/:day/:title/

# mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b' <-- This is the exact line that was in the mailchimp yml


# Authors
authors:
  keelan:
    name: Keelan Cook
    display_name: Keelan
    avatar: 'assets/images/keelan-avatar.jpg'
    gravatar: keelancook
    email: kcook@sebts.edu
    web: https://keelancook.com
    twitter: https://bsky.app/profile/keelancook.com #the code here says twitter, but this is the follow link in an author bio. It can be any website link, it appears.
    description: "Keelan Cook is the George Liele Director for the Center for Great Commission studies. He also serves as Instructor of Missiology at Southeastern Baptist Theological Seminary."
  meredith:
    name: Meredith Cook
    display_name: Meredith
    avatar: 'assets/images/avatar.png'
    gravatar: b1cc14991db7a456fcd761680bbc8f81
    email: meredithcook@proton.me
    web: https://meredithcook.net
    twitter: https://meredithcook.net #the code here says twitter, but this is the follow link in an author bio. It can be any website link, it appears.
    description: "I am married to Keelan and a stay-at-home-working mom of two tiny redheads. I serve as the Grant Coordinator for Southeastern Baptist Theological Seminary, where I earned a Master of Divinity in Missiology. I am also the author of [Go Tell Everyone: 9 Missionaries Who Shared the Good News](https://amzn.to/4fJxY6L), a children’s board book about the Great Commission and missionaries, published by B&H Kids."

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
