# Site
name: "Keelan Cook"
title: "Keelan Cook"
description: "George Liele Director of the Center for Great Commission Studies"
logo: 'assets/images/logo128.png'
favicon: 'assets/images/favicon.ico'
baseurl: /mediumish
google_analytics: 'UA-46278016-1'
disqus: ''
mailchimp-list: ''
include: ["_pages"]
permalink: /:title/

# mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b' <-- This is the exact line that was in the mailchimp yml


# Authors
authors:
  keelan:
    name: Keelan Cook
    display_name: Keelan
    avatar: 'assets/images/keelan-avatar.jpg'
    gravatar: keelancook
    email: kcook@sebts.edu
    web: https://keelancook.com
    twitter: https://twitter.com/keelancook
    description: "Keelan Cook is the George Liele Director for the Center for Great Commission studies. He also serves as Instructor of Missiology at Southeastern Baptist Theological Seminary."
  john:
    name: John
    display_name: John    
    avatar: 'assets/images/avatar.png'
    gravatar: b1cc14991db7a456fcd761680bbc8f81
    email: wowthemesnet@gmail.com
    web: https://www.wowthemes.net
    twitter: https://twitter.com/wowthemesnet
    description: "This is the author box. Write a short description of the author here. You are currently previewing Mediumish demo, a Jekyll template compatible with Github pages."

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
